//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCCRUD_Training.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MstAnswer
    {
        public int Id { get; set; }
        public string AccessID { get; set; }
        public string AnswerName { get; set; }
        public string AnswerValue { get; set; }
        public int FormTypeId { get; set; }
    }
}
