//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCCRUD_Training.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MstEmployee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MstEmployee()
        {
            this.MstEmployee1 = new HashSet<MstEmployee>();
        }
    
        public int Id { get; set; }
        public string AccessID { get; set; }
        public int OrgId { get; set; }
        public Nullable<int> EmpTypeId { get; set; }
        public string UserName { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string FullName { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string HomePhone { get; set; }
        public string CellPhone { get; set; }
        public bool VerifiedCellPhone { get; set; }
        public string Email { get; set; }
        public Nullable<int> HomeLocationID { get; set; }
        public string Title { get; set; }
        public Nullable<int> TitleID { get; set; }
        public string UserId { get; set; }
        public Nullable<int> ManagerID { get; set; }
        public bool Status { get; set; }
        public bool NotificationOverride { get; set; }
        public bool AppOverride { get; set; }
        public bool External { get; set; }
        public bool PinOnly { get; set; }
        public Nullable<int> PermissionGroupId { get; set; }
        public Nullable<int> EmpImageId { get; set; }
        public string PinNumber { get; set; }
        public string QRCode { get; set; }
        public string Signature { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public Nullable<System.DateTime> DateofJoining { get; set; }
        public Nullable<int> CountryId { get; set; }
        public string LinkedEmpId { get; set; }
        public string Settings { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MstEmployee> MstEmployee1 { get; set; }
        public virtual MstEmployee MstEmployee2 { get; set; }
    }
}
